services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - user=laravel
        - uid=1000
    depends_on:
      - db
    container_name: laravel_app
    command: ./docker-entrypoint.sh
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www:cached
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network


  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network


  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10


# Redis Service (optional)
# redis:
#   image: redis:alpine
#   container_name: laravel_redis
#   ports:
#     - "6379:6379"
#   networks:
#     - laravel-network


networks:
  laravel-network:
    driver: bridge